version: 2
build:
  image: latest
sphinx:
  configuration: docs/source/conf.py
python:
  os: ubuntu-22.04
  version: "3.10"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
